apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmixpm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmixpm-app
  template:
    metadata:
      labels:
        app: jmixpm-app
    spec:
      containers:
        - image: pm-20221116:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: jmixpm-app
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: jmixpm-db-config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jmixpm-db-config
                  key: db_password
            - name: DB_HOST
              value: jmixpm-db-service
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: HZ_NETWORK_JOIN_KUBERNETES_ENABLED
              value: "true"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 8080
            - containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: jmixpm-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      name: jmixpm-app-port
    - port: 5701
      name: jmixpm-hazelcast-port
  selector:
    app: jmixpm-app