apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmixpm-db-volume
  labels:
    type: local
    app: jmixpm-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmixpm-db-pvclaim
  labels:
    app: jmixpm-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi